name: Spam PR Detector
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  detect-spam:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Run spam detection
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTO_CLOSE: false
          SCORE_THRESHOLD: 3
        run: |
          python3 - <<'PYCODE'
          import os, re, requests, json, sys

          repo = os.environ["GITHUB_REPOSITORY"]
          token = os.environ["GITHUB_TOKEN"]
          threshold = float(os.environ.get("SCORE_THRESHOLD", 3))
          auto_close = os.environ.get("AUTO_CLOSE", "false").lower() == "true"

          event_path = os.environ.get("GITHUB_EVENT_PATH")
          with open(event_path) as f:
              event = json.load(f)
          pr = event["pull_request"]
          pr_num = pr["number"]
          api_pr_url = pr["url"]

          headers = {"Authorization": f"token {token}", "Accept": "application/vnd.github.v3+json"}
          
          # Ensure spam-pr label exists
          labels_api = f"https://api.github.com/repos/{repo}/labels"
          existing_labels = requests.get(labels_api, headers=headers).json()
          if not any(l.get("name") == "spam-pr" for l in existing_labels):
              print("Creating spam-pr label...")
              resp = requests.post(labels_api, headers=headers, json={
                  "name": "spam-pr",
                  "color": "d73a4a",
                  "description": "Detected as potential spam"
              })
              print(f"Label creation status: {resp.status_code}")
          
          files_resp = requests.get(api_pr_url + "/files", headers=headers)
          if files_resp.status_code != 200:
              print(f"Error fetching files: {files_resp.status_code}")
              sys.exit(1)
          files = files_resp.json()

          score, reasons = 0.0, []
          total_changes = sum(f["additions"] + f["deletions"] for f in files)
          changed_files = len(files)

          if total_changes <= 3:
              score += 2; reasons.append(f"tiny change ({total_changes} lines)")
          doc_only = all(re.search(r"README|CONTRIBUTING|CHANGELOG|LICENSE|\.md$", f["filename"], re.I) for f in files)
          if doc_only:
              score += 1.5; reasons.append("doc-only files")

          name_add = False
          for f in files:
              patch = f.get("patch") or ""
              added_lines = [l[1:] for l in patch.splitlines() if l.startswith("+") and not l.startswith("+++")]
              for line in added_lines:
                  if re.match(r"^[*>-]?\s*[A-Z][a-z]+ [A-Z][a-z]+$", line.strip()):
                      name_add = True; break
              if name_add: break
          if name_add:
              score += 2; reasons.append("name/handle added")

          if re.search(r"(add my name|profile|typo|contrib|author)", pr["title"], re.I):
              score += 1; reasons.append("weak/vanity title")
          if changed_files == 1:
              score += 0.5; reasons.append("single file")

          print(f"Detected score={score:.1f} reasons={reasons}")
          if score >= threshold:
              label_api = f"https://api.github.com/repos/{repo}/issues/{pr_num}/labels"
              comment_api = f"https://api.github.com/repos/{repo}/issues/{pr_num}/comments"
              
              label_resp = requests.post(label_api, headers=headers, json={"labels": ["spam-pr"]})
              print(f"Label API response: {label_resp.status_code} - {label_resp.text}")
              
              msg = (
                  "🤖 **Spam PR Detector**\n\n"
                  f"This PR appears to be low-value or spammy (score: {score:.1f}).\n\n"
                  f"Reasons: {', '.join(reasons)}.\n\n"
                  "If this is legitimate, please update the PR description to explain its purpose."
              )
              comment_resp = requests.post(comment_api, headers=headers, json={"body": msg})
              print(f"Comment API response: {comment_resp.status_code}")
              
              if auto_close:
                  pr_api = f"https://api.github.com/repos/{repo}/pulls/{pr_num}"
                  close_resp = requests.patch(pr_api, headers=headers, json={"state": "closed"})
                  print(f"Close PR response: {close_resp.status_code}")
              else:
                  print("Labeled as spam-pr.")
          else:
              print("✅ PR seems fine.")
          PYCODE
